version: 2
jobs:
  build:
    working_directory: ~/gatsby-themes
    docker:
      - image: cicleci/node:10
    steps:
      - checkout
      - restore_cache:
          name: Restoring Yarn cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Installing dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          name: Save Yarn package cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: Run Prettier check
          command: yarn prettier
      - run:
          name: Run linter
          command: yarn lint
      - run:
          name: Run Jest tests
          command: yarn test
      - store_artifacts:
          path: coverage
      - run:
          name: Send coverage reports to Codecov
          command: npx codecov
